allowBuilds:
  '@parcel/watcher': true
  '@patternslib/dev': true
  '@plone/mockup': true
  svelte-preprocess: true
  unrs-resolver: true
  yarn: false

minimumReleaseAgeExclude:
  - "@plone/mockup"

shamefullyHoist: true
nodeLinker: "hoisted"
blockExoticSubdeps: false
